### ISSUE TITLE
Username are not required to be unique

### ISSUE THREAD

**Issue by yggda** [dwetterau/alpha#3]
no check that a username is not already in use. However, user ids are unique.

**Comment by dwetterau** [comment]
Yup, I changed it in all subsequent websites: https://github.com/dwetterau/beta/blob/master/src/models/user.coffee#L7

**Comment by dwetterau** [comment]
To fix in prod remove duplicates and run something like this on the Users table:

```
ALTER IGNORE TABLE mytbl ADD UNIQUE (columnName);
```
